name: Docker images build and push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'actions-time.txt'
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ilkeiii
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Run sh
        run: |
          chmod +x get-modules.sh
          ./get-modules.sh

      - name: Docker build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.alpine
          build-args: |
            ENABLED_MODULES=http-flv-module
            NGINX_FROM_IMAGE=nginx:stable-alpine
          push: true # push to docker hub
          tags: |
              ilkeiii/nginx:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7 #,linux/386,linux/arm/v6,linux/s390x
