name: Docker images build and push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'actions-time.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: 1lkei
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
          
      - name: Run sh
        run: |
          chmod +x get-modules.sh
          ./get-modules.sh

      - name: Docker build-push
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: Dockerfile.alpine
          build-args: |
            ENABLED_MODULES=http-flv-module
            NGINX_FROM_IMAGE=nginx:stable-alpine
          push: true # push to docker hub
          tags: |
              1lkei/nginx:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7 #,linux/386,linux/arm/v6,linux/s390x

      - name: Commit updated version
        run: |
          docker pull nginx:stable-alpine
          remote_info=$(docker images nginx:stable-alpine --format '{{.Repository}}:{{.Tag}} {{.ID}}')
          echo "$remote_info" > nginx_info
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add nginx_info
          git commit -m "Update info to \"$remote_info\""
          git remote set-url origin https://1lkei:${{ secrets.REPO_BOT }}@github.com/1lkei/docker-nginx.git
          git push