name: Docker images build and push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: 1lkei
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: get image id
        run: |
          docker pull nginx:stable-alpine
          remote_info=$(docker images nginx:stable-alpine --format '{{.Repository}}:{{.Tag}} {{.ID}}')
          echo "remote_info=$remote_info" >> $GITHUB_ENV

      - name: Commit updated version
        run: |
          echo "$remote_info" > nginx_info
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add nginx_info
          git commit -m "Update info to \"$remote_info\""
          git remote set-url origin https://1lkei:${{ secrets.REPO_BOT }}@github.com/1lkei/docker-nginx.git
          git push